### ISSUE TITLE
'api_response' event handler failed - when using createTask

### ISSUE THREAD

**Issue by Prinolan009** [amazon-connect/amazon-connect-taskjs#15]
Hi

I have pasted my code below. I am able to "console.log(newTask);" and get a result, however I receive an API_response error when agent.createTask is invoked. Can you please advise where I am going wrong?

Thanks
```
	connect.agent(function(agent) {

	var queuesARNs = agent.getAllQueueARNs();
	agent.getEndpoints(
	   queuesARNs,
	   {
	      success: function(data) {
	         var endpoints = data.endpoints; // or data.addresses
	          console.log(endpoints[3]);

	          const newTask = {
	            name: "Test task from taskJS", //required, max len: 512
	            description: "N/A", //optional, max len: 4096
	            endpoint: endpoints[3], 
	            references: { //optional
	                  "reference name": { // string, max len: 4096
	                    type: "URL", //required, currently only "URL" is supported as a reference type,
	                    value: "https://www.amazon.com" //required, string, max len: 4096
	                  }
	                }
	        };//ends newTask
		console.log(newTask);
	        agent.createTask(newTask, {
	          success: function(data) { console.log("Created a task with contact id: ", data.contactId) },
	          failure: function(err) {console.log("error has occured");}
	        });//ends createTask

	      },//end success

	      failure: function(err) {
	      }

	   }//ends QueueARN
	);// ends agent.getEndpoints
});//ends connect.agent

```

**Comment by vpogudina** [comment]
I was able to create task with almost identical snippet:
`connect.agent(function(agent) {

	var queuesARNs = agent.getAllQueueARNs();
	agent.getEndpoints(
	   queuesARNs,
	   {
	      success: function(data) {
	         var endpoints = data.endpoints; // or data.addresses
	          console.log(endpoints);

	          const newTask = {
	            name: "Test task from taskJS", //required, max len: 512
	            description: "N/A", //optional, max len: 4096
	            endpoint: endpoints[0], 
	            references: { //optional
	                  "reference name": { // string, max len: 4096
	                    type: "URL", //required, currently only "URL" is supported as a reference type,
	                    value: "https://www.amazon.com" //required, string, max len: 4096
	                  }
	                }
	        };//ends newTask
		console.log(newTask);
	        agent.createTask(newTask, {
	          success: function(data) { console.log("Created a task with contact id: ", data.contactId) },
	          failure: function(err) {console.log("error has occurred");}
	        });//ends createTask

	      },//end success

	      failure: function(err) {
	      }

	   }//ends QueueARN
	);// ends agent.getEndpoints
});//ends connect.agent`

Please make sure when you referencing endpoints[3], that you do have at least 3 endpoints in array. In my snippet I had only one endpoint, so I used endpoints[0] and it successfully created a task.
