### ISSUE TITLE
- Event handler usage -

### ISSUE THREAD

**Issue by agiusalexandre** [amazon-connect/amazon-connect-taskjs#9]
I'm trying to use the Event handler : 
taskSession.onMessage((message) => console.log("The following event has occurred:", message.ContentType))

Could you please share with code snapshot to understand how it works ?

here is my code snapshot : 
`                   c.onConnecting(function (c) {
                        if (c.getType() === "task") {
                            const cnn = contact.getConnections().find(cnn => cnn.getType() === connect.ConnectionType.INBOUND);
                            if (cnn.getMediaType() === "task") {
                                console.warn("############ TASK ");
                            }
                            cnn.getMediaController().then((taskSession) => { taskSession.onMessage((message) => console.log("The following event has occurred:", message.ContentType)) });`

This event is only sent when `agent.createTask()` is called ?

many thanks,
Alex

**Comment by ctwomblyamzn** [comment]
Hi @agiusalexandre, it looks like you are expecting the ConnectionType to be `connect.ConnectionType.INBOUND`. As of now, tasks only have one connection, and its type is `connect.ConnectionType.AGENT`. If you use that connection type, you should be able to detect all of the events listed in the documentation here: https://github.com/amazon-connect/amazon-connect-taskjs#event-handlers. I'm going to close this. Please re-open if this did not solve your issue.
